// app/layout.tsx
import type { Metadata } from 'next'
import { Alexandria } from 'next/font/google'

import { cn } from '@/lib/utils'
import { Cursor } from '@/components/Cursor'

import './globals.css'

import { Toaster } from '@/components/ui/toaster'
import { SmoothScroll } from '@/components/SmoothScroll'
import { Providers } from '@/app/Providers'

import 'lenis/dist/lenis.css'

const alexandria = Alexandria({
  subsets: ['latin'],
  variable: '--font-alexandria',
  weight: ['300', '400', '500', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

// app/layout.tsx
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script src="https://js.stripe.com/v3" async />
      </head>
      <body
        className={cn(
          'max-w-page relative bg-background font-alexandria text-white antialiased dark',
          alexandria.variable
        )}
      >
        <Cursor />
        <SmoothScroll>
          <div className="pattern-overlay z-50" />
          <Providers>{children}</Providers>
          <Toaster />
        </SmoothScroll>
      </body>
    </html>
  )
}
